name: Build FRP for Android

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [arm64-v8a, armeabi-v7a, x86, x86_64]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Install Android NDK
      run: |
        sudo apt-get update
        sudo apt-get install -y android-ndk-r25c

    - name: Set up environment
      run: |
        echo "ANDROID_NDK_HOME=/usr/lib/android-ndk" >> $GITHUB_ENV
        echo "GOPATH=$HOME/go" >> $GITHUB_ENV
        echo "$HOME/go/bin" >> $GITHUB_PATH

    - name: Build FRP for Android
      env:
        GOOS: android
        CGO_ENABLED: 1
      run: |
        case ${{ matrix.arch }} in
          arm64-v8a)
            export GOARCH=arm64
            export CC=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang
            ;;
          armeabi-v7a)
            export GOARCH=arm
            export CC=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi21-clang
            ;;
          x86)
            export GOARCH=386
            export CC=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/i686-linux-android21-clang
            ;;
          x86_64)
            export GOARCH=amd64
            export CC=$ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/bin/x86_64-linux-android21-clang
            ;;
        esac
        go build -o frpc_${{ matrix.arch }} ./cmd/frpc
        go build -o frps_${{ matrix.arch }} ./cmd/frps

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: frp-android-${{ matrix.arch }}
        path: |
          frpc_${{ matrix.arch }}
          frps_${{ matrix.arch }}
